# Prometheus Configuration for OTLP Stack
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# 规则文件
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# 抓取配置
scrape_configs:
  # Prometheus自身指标
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # OTEL Agent指标
  - job_name: 'otel-agent'
    static_configs:
      - targets: ['otel-agent:8888']
    scrape_interval: 15s
    metrics_path: /metrics

  # OTEL Collector指标
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
    scrape_interval: 15s
    metrics_path: /metrics

  # VictoriaLogs指标
  - job_name: 'victorialogs'
    static_configs:
      - targets: ['victorialogs:9428']
    scrape_interval: 30s
    metrics_path: /metrics

# 远程写入配置（用于接收OTEL Collector的指标）
remote_write:
  - url: "http://localhost:9090/api/v1/write"